_base: [secrets]

#_meta.script_name: rephrase
_meta.script_name: generate-arithmetic
#outdir: data/new

skip-confirm: yes

overwrite: yes

n: 8

#path: data/Arithmetic
path: data/depth1_func25/0.csv



